#!/bin/bash

output=$(/usr/bin/snmpget -v 2c -c public -Ovq openwrt 1.3.6.1.4.1.2021.10.1.3.2)
load5=${output//\"/}

retval=$(echo "$load5 > 1.73" |bc)
if [[ $retval -eq 1 ]]; then
  echo "BAD;5 minute load average is $load5"
else
  echo "OK;5 minute load average is $load5"
fi
