#!/bin/bash

SCRIPT_PATH=$(dirname $(realpath $BASH_SOURCE))

. "$SCRIPT_PATH/common.sh"

output=$(/usr/bin/snmpget -v 2c -c public -Ovq lede 1.3.6.1.4.1.2021.10.1.3.2)
load5=${output//\"/}

retval=$(echo "$load5 > 1.73" |/usr/bin/bc)
if [[ $retval -eq 1 ]]; then
  echo "BAD;5 minute load average is $load5"
else
  echo "OK;5 minute load average is $load5"
fi
