#!/bin/sh

[ -z $1 ] && echo "$0: must supply service name" >&2 && exit 1

service=$1

retval=$(systemctl is-active ${service}.service)
case $retval in
inactive)
  echo "BAD;$service is inactive"
  ;;
active)
  echo "OK;$service is active"
  ;;
*)
  echo "UNKNOWN;$service is in an unknown state ($retval)"
  ;;
esac
