#!/bin/sh

[ -z $1 ] && echo "usage: $0 <url>" >&2 && exit 1

url=$1

curl -s -k -f -m 10 -o /dev/null "$url"
if [ $? -eq 0 ]; then
  echo "OK;Good HTTP Response"
else
  echo "BAD;Error fetching URL"
fi

