#!/bin/sh

[ -z $1 ] && echo "$0: must supply hostname/IP address" >&2 && exit 1

host=$1

url="https://openwrt.org/toh/hwdata/tp-link/tp-link_archer_c7_ac1750_v2.0"

current_version=$(ssh $host 'cat /etc/openwrt_release' |awk -F= '$1=="DISTRIB_RELEASE" {print $2}')
current_version=${current_version#\'}
current_version=${current_version%\'}

if ! curl -s -o /tmp/router_current_rel "$url"; then
  echo "UNKNOWN;Error retrieving device info page"
else
  supported_current_rel=$(grep -o -E '<dd class="supported_current_rel">\S+</dd>' /tmp/router_current_rel |grep -o -E '[[:digit:].]+')

  if [ "$current_version" != "$supported_current_rel" ]; then
    echo "BAD;Current Version: $current_version. Current Release: $supported_current_rel"
  else
    echo "OK;Current Version: $current_version"
  fi
fi
