#!/bin/bash

SCRIPT_PATH=$(dirname $(realpath $BASH_SOURCE))

. "$SCRIPT_PATH/common.sh"

if [[ -e /var/run/reboot-required ]]; then
  echo "BAD;Reboot required"
else
  echo "OK;No reboot required"
fi
