#!/bin/bash

SCRIPT_PATH=$(dirname $(realpath $BASH_SOURCE))

. "$SCRIPT_PATH/common.sh"

if [[ -z $1 ]]; then
  echo "$0: must supply process name" >&2
  exit -1
fi

proc=$1

if ! /usr/bin/pgrep "$proc" >/dev/null 2>&1; then
  echo "BAD;$proc is not running"
else
  echo "OK;$proc is running"
fi
