#!/bin/bash

SCRIPT_PATH=$(dirname $(realpath $BASH_SOURCE))

. "$SCRIPT_PATH/common.sh"

[[ -z $1 ]] && echo "usage: $0 <url>" >&2 && exit 1

url=$1

if curl -s -I -o /dev/null "$url"; then
  echo "OK;Good HTTP Response"
else
  echo "BAD;Error fetching URL"
fi

