#!/bin/sh

OS_TYPE=
if [ -r /etc/os-release ]; then
  . /etc/os-release
  if [ -n ID_LIKE ]; then
    OS_TYPE=$ID_LIKE
  fi
fi 

case "$OS_TYPE" in
"rhel fedora")
  latest_kernel=$(rpm -q kernel --last |head -1 |awk '{print $1}' |sed -e 's/^kernel-//')
  running_kernel=$(uname -r)

  if [ "$latest_kernel" != "$running_kernel" ]; then
    echo "BAD;Reboot required"
  else
    echo "OK;No reboot required"
  fi
  ;;
"debian")
  if [ -e /var/run/reboot-required ]; then
    echo "BAD;Reboot required"
  else
    echo "OK;No reboot required"
  fi
  ;;
*)
  echo "Couldn't determine OS Type" >&2
  exit 1
esac
