#!/bin/sh

threshold=4

[ -z $1 ] && echo "usage: $0 <container>" && exit 1

last_error_count=-1
container=$1
prev_run="/tmp/http_errors-$container"
if [ -e "$prev_run" ]; then
  last_error_count=$(cat "$prev_run")
fi
num_errors=$($HOME/scripts/docker_http_errors -c "$container")
echo $num_errors >"$prev_run"
delta_errors=$((num_errors - last_error_count))
if [ $((delta_errors >= threshold)) -eq 1 ]; then
  echo "BAD;More than $threshold errors in the last five minutes ($delta_errors) - $num_errors total for day"
else
  echo "OK;Number of errors ($num_errors total / $delta_errors last 5 minutes) below threshold ($threshold)"
fi
