#!/bin/bash

[[ -z $1 ]] && echo "$0: must supply hostname/IP address" >&2 && exit 1

host=$1

output=$(ssh $host uptime)
load_avgs="${output##*:}"
load_avgs="${load_avgs#*, }"
load5="${load_avgs%,*}"

retval=$(echo "$load5 > 1.73" |bc)
if [[ $retval -eq 1 ]]; then
  echo "BAD;5 minute load average is $load5"
else
  echo "OK;5 minute load average is $load5"
fi
