#!/bin/sh

[ -z $1 ] && echo "$0: must supply process name" >&2 && exit 1

proc=$1

if ! pgrep "$proc" >/dev/null 2>&1; then
  echo "BAD;$proc is not running"
  #$HOME/scripts/restart_proc.sh $proc
else
  echo "OK;$proc is running"
fi
