#!/bin/sh

threshold=1

[ -z "$1" ] && echo "usage: $0 <file>" && exit 1
[ -z "$2" ] && type=""
[ -n "$2" ] && type="$2_"

last_error_count=-1
filename=$(basename $1)
prev_run="/tmp/http_errors-$filename"
if [ -e "$prev_run" ]; then
  last_error_count=$(cat "$prev_run")
fi
num_hosts=$(http_errors -c)
if [ $((num_hosts >= threshold)) -eq 1 ]; then
  echo "BAD;Hosts that have more than 10 errors in the last 5 minutes - $num_errors total for day"
else
  echo "OK;No hosts with more than 10 errors in the last 5 minutes"
fi
