#!/bin/bash

SCRIPT_PATH=$(dirname $(realpath $BASH_SOURCE))

. "$SCRIPT_PATH/common.sh"

if [[ -z $1 ]]; then
  echo "$0: must supply service name" >&2
  exit -1
fi

service=$1

retval=$(/bin/systemctl is-active ${service}.service)
case $retval in
inactive)
  echo "BAD;$service is inactive"
  ;;
active)
  echo "OK;$service is active"
  ;;
*)
  echo "UNKNOWN;$service is in an unknown state ($retval)"
  ;;
esac
