#!/bin/bash
SCRIPT_PATH=$(dirname $(realpath $BASH_SOURCE))
. "$SCRIPT_PATH/common.sh"

if [[ -z $1 ]]; then
  echo "$0: must supply output path" >&2
  exit 1
fi

status_file=$1
output_file=$2

read -r -d '' output_start <<'OUTPUT_START'
<!DOCTYPE html>
<html lang"en-US">
<head>
  <meta charset="UTF-8">
  <title>Monitoring</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <header class="header">
  </header>
  <section class="monitors">
    <h2>Monitor List</h2>
    <table>
      <thead>
        <tr>
          <th>Target</th>
          <th>Type</th>
          <th>State</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody id="monitor_list">
OUTPUT_START

lastchange=$(stat -c '%y' "$status_file" |cut -d. -f1)
lastrefresh=$(date +"%Y-%m-%d %H:%M:%S")

read -r -d '' output_end <<OUTPUT_END
      </tbody>
    </table>
  </section>
  <footer>
    <div>
      <div>
        <ul>
          <li>Last Change: <span id="last_updated">$lastchange</span></li>
          <li>Last Refresh: <span id="status">{{.NowDate}}</span></li>
          <li>Your IP: <span id="remote_addr">{{.IP}}</span></li>
        </ul>
      </div>
    </div>
  </footer>
</body>
</html>

OUTPUT_END

output_middle=""
while read -r line; do
  [[ $line =~ ^# ]] && continue
  name=${line%%,*}
  type=${line#*,}
  type=${type%%,*}
  state=${line%,*}
  state=${state##*,}
  status=${line##*,}

  read -r -d '' output_middle <<-OUTPUT_MIDDLE
        $output_middle
        <tr><td>$name</td><td>$type</td><td>$state</td><td>$status</td></tr>
OUTPUT_MIDDLE

done < <(sort -n "$status_file")
echo -e "$output_start\n$output_middle\n$output_end" > "$output_file"


