#!/bin/bash

if [ $(echo "$0" | grep '/') ]; then
  APP_HOME=${0%/*}

  if [ "$APP_HOME" = "." ]; then
    APP_HOME="$PWD"
  fi
fi
export APP_HOME

for script in $APP_HOME/check_*; do
  if [ -x "$script" ]; then
    "$script"
  fi
done

$APP_HOME/create_html

