#!/bin/bash
# Required flags for production use
set -u
set -e

APP_HOME="."
[[ $0 =~ / ]] && APP_HOME=${0%/*}
export APP_HOME

for script in $APP_HOME/check_*; do
  $script
done

$APP_HOME/create_html

