#!/bin/bash
curl -s -o /dev/null -X POST --header "Content-Type: application/json" --request POST --data-binary "{\"value1\":\"$1\",\"value2\":\"$2\"}" https://maker.ifttt.com/use/${IFTTT_API_KEY}/monitoring_event
